# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3942e7e0aeb3d6f3f98fd1fd09f416722355dec54645e65d6613444924254c4b0507358be887eca187c881c84926f528c8e9fcfde053c7b37878d06d8ccc655

test:
  secret_key_base: 43c856544d65a19f2227c54ff4f236d612ae16da2d41aa318343343dceeb2c01ef10b17bdb76e837a01c9c72976356f9eb27db96e806b85f3603b3fe8dfd9b4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
